on:
  push:
    branches:
      - main
      - test1
  workflow_dispatch:
    inputs:
      git_ref:
        description: Test1

permissions:
  id-token: write
  contents: read

jobs:
  Code-Test:
    name: Build Test
    runs-on: window-latest
    environment: DEV
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with: ${{ inputs.git_ref }}
